"use client";
import { FormEvent, Suspense, useState } from "react";
import { useSearchParams } from "next/navigation";
import { CheckCircle2, Loader2 } from "lucide-react";
import AppShell from "@/components/layout/AppShell";

function ResetPasswordContent() {
  const params = useSearchParams();
  const token = params.get("token");
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(""); setMessage(""); try { const response = await fetch("/api/auth/password-reset", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(token ? { token, password } : { email }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error); setMessage(token ? "Your password has been changed. You can sign in again." : "If an account exists for that email, a secure reset link is on its way."); } catch (resetError) { setError(resetError instanceof Error ? resetError.message : "Unable to continue."); } finally { setBusy(false); } }
  return <AppShell title="Reset password"><div className="mx-auto max-w-md px-5 py-16"><div className="rounded-3xl border bg-white p-8 shadow-sm" style={{ borderColor: "var(--kv-border-light)" }}><p className="heritage-caption" style={{ color: "var(--kv-primary)" }}>Account recovery</p><h1 className="heritage-heading mt-2 text-3xl font-semibold" style={{ color: "var(--kv-text)" }}>{token ? "Choose a new password" : "Reset your password"}</h1><p className="mt-3 text-sm leading-6" style={{ color: "var(--kv-text-secondary)" }}>{token ? "Use at least 12 characters. All existing sessions will be signed out." : "Enter your email and we will send a secure, time-limited recovery link."}</p>{message ? <div className="mt-6 rounded-xl bg-[#E9F8F0] p-4 text-sm text-[#176B46]"><CheckCircle2 className="mb-2 h-5 w-5" />{message}</div> : <form onSubmit={submit} className="mt-6 space-y-4">{token ? <label className="block text-sm font-semibold">New password<input required minLength={12} type="password" value={password} onChange={(event) => setPassword(event.target.value)} className="mt-2 w-full rounded-xl border px-4 py-3 font-normal" placeholder="At least 12 characters" /></label> : <label className="block text-sm font-semibold">Email address<input required type="email" value={email} onChange={(event) => setEmail(event.target.value)} className="mt-2 w-full rounded-xl border px-4 py-3 font-normal" placeholder="alex@example.com" /></label>}{error && <p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<button disabled={busy} className="flex w-full items-center justify-center gap-2 rounded-xl px-5 py-3.5 text-sm font-semibold text-white disabled:opacity-60" style={{ background: "var(--kv-primary)" }}>{busy ? <Loader2 className="h-4 w-4 animate-spin" /> : token ? "Change password" : "Send reset link"}</button></form>}</div></div></AppShell>;
}

export default function ResetPasswordPage() { return <Suspense fallback={<div className="min-h-[60vh]" />}><ResetPasswordContent /></Suspense>; }
