import { useState } from "react";
import { ActivityIndicator, KeyboardAvoidingView, Platform, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { useRouter } from "expo-router";
import { colors } from "@/constants/theme";
import { api } from "@/lib/api";
export default function LoginScreen() { const router = useRouter(); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  async function submit() { if (!email.trim() || !password) { setError("Enter your email and password."); return; } setLoading(true); setError(""); try { await api.login(email, password); router.replace("/(tabs)/trip"); } catch (loginError) { setError(loginError instanceof Error ? loginError.message : "Unable to sign in."); } finally { setLoading(false); } }
  return <KeyboardAvoidingView style={styles.page} behavior={Platform.OS === "ios" ? "padding" : undefined}><View style={styles.mark}><Text style={styles.markText}>KV</Text></View><Text style={styles.eyebrow}>WELCOME BACK</Text><Text style={styles.title}>Continue your{`\n`}journey.</Text><Text style={styles.copy}>Sign in to sync your bookings and keep your plans close.</Text><View style={styles.form}><Text style={styles.label}>Email address</Text><TextInput value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address" placeholder="you@example.com" placeholderTextColor={colors.muted} style={styles.input} /><Text style={styles.label}>Password</Text><TextInput value={password} onChangeText={setPassword} secureTextEntry placeholder="Your password" placeholderTextColor={colors.muted} style={styles.input} />{error ? <Text style={styles.error}>{error}</Text> : null}<Pressable onPress={submit} disabled={loading} style={({ pressed }) => [styles.button, pressed && { opacity: .75 }]}>{loading ? <ActivityIndicator color={colors.surface} /> : <Text style={styles.buttonText}>Sign in securely</Text>}</Pressable></View><Pressable onPress={() => router.back()}><Text style={styles.back}>Continue as guest</Text></Pressable></KeyboardAvoidingView> }
const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: colors.bg, padding: 25, justifyContent: "center" }, mark: { width: 49, height: 49, borderRadius: 17, backgroundColor: colors.purple, alignItems: "center", justifyContent: "center", marginBottom: 28 }, markText: { color: colors.surface, fontWeight: "900", fontSize: 15 }, eyebrow: { color: colors.terracotta, fontSize: 10, letterSpacing: 1.5, fontWeight: "800" }, title: { color: colors.ink, fontSize: 34, lineHeight: 37, fontWeight: "800", marginTop: 8 }, copy: { color: colors.muted, fontSize: 14, lineHeight: 20, marginTop: 12, maxWidth: 310 }, form: { marginTop: 28, gap: 8 }, label: { color: colors.ink, fontSize: 12, fontWeight: "800", marginTop: 7 }, input: { height: 50, borderRadius: 14, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, paddingHorizontal: 14, color: colors.ink, fontSize: 14 }, error: { color: "#A13E38", fontSize: 12, lineHeight: 17, marginTop: 4 }, button: { height: 51, borderRadius: 14, backgroundColor: colors.purple, alignItems: "center", justifyContent: "center", marginTop: 10 }, buttonText: { color: colors.surface, fontSize: 14, fontWeight: "800" }, back: { color: colors.purple, textAlign: "center", fontWeight: "800", fontSize: 13, marginTop: 24 } });
