import { useEffect, useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { useRouter } from "expo-router";
import { Ionicons } from "@expo/vector-icons";
import { colors } from "@/constants/theme";
import { api, type Apartment } from "@/lib/api";

const actions = [{ icon: "airplane-outline", label: "Find a flight", route: "/explore" }, { icon: "home-outline", label: "Find a stay", route: "/explore" }, { icon: "sparkles-outline", label: "Ask KEVESTA", route: "/assistant" }, { icon: "book-outline", label: "Arrival guide", route: "/explore" }] as const;
export default function HomeScreen() {
  const router = useRouter(); const [stays, setStays] = useState<Apartment[]>([]);
  useEffect(() => { api.getFeaturedStays().then((data) => setStays(data.apartments || [])).catch(() => setStays([])); }, []);
  return <ScrollView style={styles.page} contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
    <View style={styles.header}><View><Text style={styles.eyebrow}>YOUR WORLD, MADE SIMPLE</Text><Text style={styles.title}>Welcome to{`\n`}KEVESTA.</Text></View><Pressable style={styles.avatar} onPress={() => router.push("/trip")}><Text style={styles.avatarText}>KV</Text></Pressable></View>
    <View style={styles.hero}><View style={styles.heroOrb} /><Text style={styles.heroKicker}>PLAN WITH CONFIDENCE</Text><Text style={styles.heroTitle}>Where are you{`\n`}headed next?</Text><Text style={styles.heroCopy}>Personalized travel and relocation guidance, all in one calm place.</Text><Pressable style={styles.heroButton} onPress={() => router.push("/assistant")}><Text style={styles.heroButtonText}>Start planning</Text><Ionicons name="arrow-forward" size={18} color={colors.surface} /></Pressable></View>
    <Text style={styles.sectionTitle}>What do you need?</Text><View style={styles.actionGrid}>{actions.map((action) => <Pressable key={action.label} style={({ pressed }) => [styles.action, pressed && styles.pressed]} onPress={() => router.push(action.route as never)}><View style={styles.actionIcon}><Ionicons name={action.icon as never} size={21} color={colors.purple} /></View><Text style={styles.actionLabel}>{action.label}</Text><Ionicons name="chevron-forward" size={16} color={colors.muted} /></Pressable>)}</View>
    {stays.length > 0 && <><View style={styles.sectionRow}><Text style={styles.sectionTitle}>Featured stays</Text><Pressable onPress={() => router.push("/explore")}><Text style={styles.seeAll}>See all</Text></Pressable></View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{ gap: 12 }}>{stays.slice(0, 5).map((stay) => <Pressable key={stay.id} style={styles.stayCard} onPress={() => router.push("/explore")}><View style={styles.stayImage}><Text style={styles.stayEmoji}>⌂</Text></View><Text style={styles.stayTitle} numberOfLines={1}>{stay.title}</Text><Text style={styles.stayMeta}>{stay.city} · {stay.currency} {stay.price}/{stay.priceUnit}</Text></Pressable>)}</ScrollView></>}
  </ScrollView>;
}
const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: colors.bg }, content: { padding: 22, paddingTop: 18, paddingBottom: 32 }, header: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 22 }, eyebrow: { color: colors.terracotta, fontSize: 10, letterSpacing: 1.5, fontWeight: "800", marginBottom: 7 }, title: { color: colors.ink, fontSize: 31, lineHeight: 34, fontWeight: "800", letterSpacing: -0.8 }, avatar: { width: 42, height: 42, borderRadius: 21, backgroundColor: colors.purple, alignItems: "center", justifyContent: "center" }, avatarText: { color: colors.surface, fontWeight: "800", fontSize: 12 }, hero: { overflow: "hidden", borderRadius: 24, padding: 22, backgroundColor: colors.purple, minHeight: 216, marginBottom: 28 }, heroOrb: { position: "absolute", right: -42, top: -54, width: 190, height: 190, borderRadius: 100, backgroundColor: "#705B91" }, heroKicker: { color: "#D8CFE7", fontSize: 10, letterSpacing: 1.3, fontWeight: "800" }, heroTitle: { color: colors.surface, fontSize: 29, lineHeight: 32, fontWeight: "800", marginTop: 9 }, heroCopy: { color: "#DDD5E7", fontSize: 13, lineHeight: 19, marginTop: 8, maxWidth: 250 }, heroButton: { alignSelf: "flex-start", flexDirection: "row", alignItems: "center", gap: 8, backgroundColor: colors.terracotta, paddingHorizontal: 15, paddingVertical: 11, borderRadius: 13, marginTop: 16 }, heroButtonText: { color: colors.surface, fontWeight: "800", fontSize: 13 }, sectionTitle: { fontSize: 18, fontWeight: "800", color: colors.ink, marginBottom: 13 }, actionGrid: { flexDirection: "row", flexWrap: "wrap", gap: 10, marginBottom: 27 }, action: { width: "48%", minHeight: 100, padding: 13, borderRadius: 17, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, justifyContent: "space-between" }, actionIcon: { width: 35, height: 35, borderRadius: 11, backgroundColor: colors.purpleSoft, alignItems: "center", justifyContent: "center" }, actionLabel: { color: colors.ink, fontSize: 13, fontWeight: "700", marginTop: 10 }, pressed: { opacity: 0.72, transform: [{ scale: 0.98 }] }, sectionRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, seeAll: { color: colors.purple, fontSize: 12, fontWeight: "800", marginBottom: 13 }, stayCard: { width: 170, backgroundColor: colors.surface, borderRadius: 17, padding: 8, borderWidth: 1, borderColor: colors.border }, stayImage: { height: 92, backgroundColor: "#E8DED2", borderRadius: 12, alignItems: "center", justifyContent: "center" }, stayEmoji: { fontSize: 34, color: colors.terracotta }, stayTitle: { color: colors.ink, fontWeight: "800", fontSize: 13, marginTop: 9 }, stayMeta: { color: colors.muted, fontSize: 11, marginTop: 3 } });
