const escapeHtml = (value: string) => value.replace(/[&<>"']/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[character] || character);

function shell(preheader: string, eyebrow: string, title: string, body: string, actionLabel: string, actionUrl: string, footer: string) {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>${escapeHtml(title)}</title></head><body style="margin:0;background:#f5f2ed;color:#17243a;font-family:Arial,Helvetica,sans-serif"><div style="display:none;max-height:0;overflow:hidden;opacity:0">${escapeHtml(preheader)}</div><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:#f5f2ed;padding:32px 12px"><tr><td align="center"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:600px;background:#fff;border:1px solid #e6e0d8;border-radius:24px;overflow:hidden"><tr><td style="background:#17243a;padding:28px 32px"><div style="font-size:22px;font-weight:700;letter-spacing:.08em;color:#fff">KEVESTA</div><div style="margin-top:7px;color:#aebbd0;font-size:12px;letter-spacing:.16em;text-transform:uppercase">Move with confidence</div></td></tr><tr><td style="padding:40px 32px 36px"><div style="color:#2f72e8;font-size:12px;font-weight:700;letter-spacing:.16em;text-transform:uppercase">${escapeHtml(eyebrow)}</div><h1 style="margin:12px 0 16px;font-size:30px;line-height:1.15;color:#17243a">${escapeHtml(title)}</h1><div style="font-size:16px;line-height:1.7;color:#52627a">${body}</div><p style="margin:30px 0"><a href="${escapeHtml(actionUrl)}" style="display:inline-block;background:#2f72e8;color:#fff;text-decoration:none;border-radius:12px;padding:14px 22px;font-size:15px;font-weight:700">${escapeHtml(actionLabel)}</a></p><p style="font-size:13px;line-height:1.6;color:#8a98aa">If you did not request this, you can safely ignore this email. The link expires automatically.</p></td></tr><tr><td style="border-top:1px solid #eee8e0;padding:22px 32px;color:#8a98aa;font-size:12px;line-height:1.6">${footer}<br><span style="color:#b2bac5">KEVESTA · Travel, relocation, and trusted local support</span></td></tr></table></td></tr></table></body></html>`;
}

export function verificationEmail(name: string, url: string) { return { subject: "Confirm your KEVESTA email", html: shell("One quick step to secure your KEVESTA account.", "Account security", `Welcome to KEVESTA, ${name}`, "Confirm your email to unlock secure booking and keep your trips connected.", "Confirm my email", url, "You are receiving this because an account was created with this email address.") }; }
export function passwordResetEmail(name: string, url: string) { return { subject: "Reset your KEVESTA password", html: shell("A secure password reset link for your KEVESTA account.", "Password reset", `Reset your password, ${name}`, "Choose a new password to get back to your trips, bookings, and relocation plans.", "Choose a new password", url, "If you did not request a password reset, no changes have been made to your account.") }; }

export function refundRequestedEmail(name: string, bookingTitle: string, amount: string, receiptNumber: string, url: string) {
  return { subject: "Your KEVESTA refund request is recorded", html: shell("Your KEVESTA refund request has been recorded.", "Refund request", `Refund request received, ${name}`, `<p>We recorded your request for <strong>${escapeHtml(bookingTitle)}</strong>.</p><p>Amount: <strong>${escapeHtml(amount)}</strong><br>Receipt reference: <strong>${escapeHtml(receiptNumber)}</strong></p><p>Your refund remains pending until the payment provider confirms completion.</p>`, "View my trips", url, "Keep this receipt reference for support questions about your refund.") };
}

export function refundCompletedEmail(name: string, bookingTitle: string, amount: string, receiptNumber: string, providerReference: string, url: string) {
  return { subject: "Your KEVESTA refund is complete", html: shell("Your KEVESTA refund has been confirmed.", "Refund complete", `Refund confirmed, ${name}`, `<p>Your refund for <strong>${escapeHtml(bookingTitle)}</strong> is complete.</p><p>Amount returned: <strong>${escapeHtml(amount)}</strong><br>Receipt reference: <strong>${escapeHtml(receiptNumber)}</strong><br>Provider reference: <strong>${escapeHtml(providerReference)}</strong></p>`, "View my trips", url, "This receipt confirms the provider-reported refund completion.") };
}
