import { Platform } from "react-native";
import * as SecureStore from "expo-secure-store";
import AsyncStorage from "@react-native-async-storage/async-storage";
export type Country = { code: string; name: string; flag: string; currency: string; language: string; timezone?: string };
export type GuidanceCategory = { id: string; title: string; icon: string; description: string; items: { id: string; title: string; content: string; tags: string[] }[] };
export type Apartment = { id: string; title: string; location: string; city: string; country: string; price: number; currency: string; priceUnit: string; images: string[]; bedrooms: number; bathrooms: number; maxGuests: number; rating: number; reviewCount: number; amenities: string[]; featured?: boolean; description?: string; houseRules?: string[]; availability?: { checkIn: string; checkOut: string } };
export type Flight = { id: string; airline: string; flightNumber: string; origin: { code: string; city: string }; destination: { code: string; city: string }; departureTime: string; arrivalTime: string; duration: string; stops: number; price: number; currency: string; baggage: string };
export type User = { id: string; email: string; name: string } | null;
export type Booking = { id: string; item_type: string; item_id: string; item_title: string; amount: number; currency: string; status: string; payment_status: string | null; created_at: string; updated_at: string };
export type Trip = { id: string; name: string; destination?: string; start_date?: string; end_date?: string; country_code?: string; cover_image?: string; role?: string };
export type TripWorkspace = { trip: Trip; members: { id: string; email: string; name?: string; role: string; status: string }[]; stops: { id: string; title: string; description?: string; location?: string; category: string; start_at?: string; end_at?: string }[]; documents: { id: string; title: string; document_type: string; reference?: string; expires_at?: string }[]; expenses: { id: string; description: string; amount_cents: number; currency: string; paid_by_name?: string }[]; notes: { id: string; title: string; body: string }[]; links: { id: string; title: string; url: string }[]; photos: { id: string; url: string; caption?: string }[] };
export type BookingIntent = { id: string; itemType: string; itemId: string; title: string; amount: number; currency: string; expiresAt: string };
export type Payment = { mode: "column" | "setup_required"; status: string; paymentId: string; message?: string };
const API_BASE = process.env.EXPO_PUBLIC_API_URL || "http://localhost:3000"; const TOKEN_KEY = "kevesta_mobile_token"; const TRIP_CACHE_KEY = "kevesta_trip_cache";
async function getToken() { return Platform.OS === "web" ? (typeof localStorage === "undefined" ? null : localStorage.getItem(TOKEN_KEY)) : SecureStore.getItemAsync(TOKEN_KEY); }
async function saveToken(token: string) { if (Platform.OS === "web") localStorage.setItem(TOKEN_KEY, token); else await SecureStore.setItemAsync(TOKEN_KEY, token, { keychainAccessible: SecureStore.WHEN_UNLOCKED_THIS_DEVICE_ONLY }); }
async function clearToken() { if (Platform.OS === "web") localStorage.removeItem(TOKEN_KEY); else await SecureStore.deleteItemAsync(TOKEN_KEY); }
async function request<T>(path: string, init?: RequestInit, authenticated = false): Promise<T> { const token = authenticated ? await getToken() : null; const response = await fetch(`${API_BASE}${path}`, { ...init, headers: { Accept: "application/json", "Content-Type": "application/json", ...(token ? { Authorization: `Bearer ${token}` } : {}), ...(init?.headers || {}) } }); const data = await response.json(); if (response.status === 401 && authenticated) await clearToken(); if (!response.ok) throw new Error(data?.error || "Something went wrong"); return data as T; }
async function cacheTrip(data: TripWorkspace) { await AsyncStorage.setItem(TRIP_CACHE_KEY, JSON.stringify(data)); }
async function cachedTrip() { const raw = await AsyncStorage.getItem(TRIP_CACHE_KEY); return raw ? JSON.parse(raw) as TripWorkspace : null; }
export const api = {
  login: async (email: string, password: string) => { const data = await request<{ token: string; expiresAt: string; user: Exclude<User, null> }>("/api/auth/mobile/login", { method: "POST", body: JSON.stringify({ email, password }) }); await saveToken(data.token); return data; }, logout: async () => { try { await request("/api/auth/mobile/logout", { method: "POST" }, true); } finally { await clearToken(); } }, hasToken: async () => Boolean(await getToken()),
  getUser: () => request<{ user: User }>("/api/auth/me", undefined, true), getTravel: (country?: string) => request<{ countries: Country[]; categories: GuidanceCategory[]; country?: Country }>(`/api/travel${country ? `?country=${country}` : ""}`), getFeaturedStays: () => request<{ apartments: Apartment[] }>("/api/apartments?action=featured"), getApartment: (id: string) => request<{ apartment: Apartment }>(`/api/apartments/${encodeURIComponent(id)}`),
  getFlights: (origin: string, destination: string, departDate?: string, passengers = 1, cabinClass = "economy") => request<{ flights: Flight[] }>(`/api/flights?origin=${encodeURIComponent(origin)}&destination=${encodeURIComponent(destination)}&departDate=${encodeURIComponent(departDate || new Date(Date.now() + 14 * 86400000).toISOString().slice(0, 10))}&passengers=${passengers}&cabinClass=${encodeURIComponent(cabinClass)}`), chat: (message: string, country: string, conversationHistory: { role: string; content: string }[] = []) => request<{ response: string }>("/api/chat", { method: "POST", body: JSON.stringify({ message, country, type: "travel", conversationHistory }) }),
  getBookings: () => request<{ bookings: Booking[] }>("/api/bookings", undefined, true), createIntent: (body: { itemType: "apartment" | "flight"; itemId: string; origin?: string; destination?: string; departDate?: string; cabinClass?: string; passengers?: number; seatPrice?: number }) => request<{ intent: BookingIntent }>("/api/bookings/intents", { method: "POST", body: JSON.stringify(body) }, true), startBankPayment: (intentId: string, customerName: string, customerEmail: string, idempotencyKey: string) => request<{ payment: Payment; intent: { id: string; amount: number; currency: string; title: string } }>("/api/payments", { method: "POST", headers: { "Idempotency-Key": idempotencyKey }, body: JSON.stringify({ intentId, customerName, customerEmail }) }, true),
  listTrips: () => request<{ trips: Trip[] }>("/api/trips", undefined, true), createTrip: (body: { name: string; destination?: string; countryCode?: string; startDate?: string; endDate?: string }) => request<{ trip: Trip }>("/api/trips", { method: "POST", body: JSON.stringify(body) }, true),
  getTrip: async (id: string) => { try { const data = await request<TripWorkspace>(`/api/trips/${id}`, undefined, true); await cacheTrip(data); return data; } catch (error) { const cached = await cachedTrip(); if (cached?.trip.id === id) return cached; throw error; } }, updateTrip: (body: { tripId: string; action: string; [key: string]: unknown }) => request<Record<string, unknown>>("/api/trips", { method: "PUT", body: JSON.stringify(body) }, true),
};
